### ISSUE TITLE
Billing: Send invoice using our notification framework (link to our front-end + download)

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1893]

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane 
Could you merge with master-qa?
Thanks.

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane
> Could you merge with master-qa?
> Thanks.

I think you mean @Ninjeneer

**Comment by LucasBrazi06** [comment]
> > @mahdibenromdhane
> > Could you merge with master-qa?
> > Thanks.
> 
> I think you mean @Ninjeneer

Yes lol ! :-D
@Ninjeneer
Could you merge with master-qa?

**Comment by Ninjeneer** [comment]
@LucasBrazi06 Do you mean merging master-qa into both branches, or merging both branches into master-qa ?

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 Do you mean merging master-qa into both branches, or merging both branches into master-qa ? If so, I am not allowed to self approve PR :)

Sync your branch with the latest changes in master-qa ;-)
git merge origin master-qa

**Comment by Ninjeneer** [comment]
Done

**Comment by LucasBrazi06** [comment]
@Ninjeneer 
You forgot to put it back to the right pipeline.
